language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
notifications:
  hipchat:
    rooms:
      secure: LdpVRQbAMEiEupJUjytavciJb9XTbv3pc/Ul3y9zU9KV3rlEmRwho/dEdtqNHz7U5rPVAMQKRq88LnLjM131xrBAu8+QxxApGOoYgxc3YJtFUmsYVipVIY3OoTaM+HfoaGCb/47I8RB8m7wSNUOHOVMi+Qf7qBklDlSi0/kVn3g=
